version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.9
      - image: mongo:latest
    working_directory: ~/repo

jobs:
  build:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Update & Install Dependencies
          command: |
            apt-get update
            apt-get install -y gcc g++
            pip install -r requirements.txt
      - run:
          name: Compile C++ File
          command: |
            echo "Compiling C++ file into binary..."
            gcc raj.c -o raja -pthread || exit 1
            chmod +x raja
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  test:
    executor: python-executor
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Start MongoDB
          command: |
            echo "Checking MongoDB connection..."
            until nc -z localhost 27017; do sleep 1; done
            echo "MongoDB is up and running!"
      - run:
          name: Run the Application
          command: |
            echo "Running the compiled binary..."
            bash -c 'while true; do echo "Still running..."; pip install -r requirements.txt && chmod +x * && python3 raja.py || echo "Application crashed. Restarting..."; sleep 5; done'

  trigger_next_pipeline:
    executor: python-executor
    steps:
      - run:
          name: Trigger Next Pipeline
          command: |
            curl -X POST "https://circleci.com/api/v2/project/gh/YOUR_ORG/YOUR_REPO/pipeline" \
                 -H "Circle-Token: $CCIPRJ_5AjsQPJvUCmbsweGJ33cit_7aefcf669eb74e32997382e6fca0042ef6d996df" \
                 -H "Content-Type: application/json" \
                 -d '{"branch": "main"}'

workflows:
  version: 2
  full_pipeline:
    jobs:
      - build
      - test:
          requires:
            - build
      - trigger_next_pipeline:
          requires:
            - test
