name: Auto Deploy

on:
  push:
    branches:
      - main  # Main branch push होते ही deploy होगा

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Python version, जरूरत के हिसाब से बदलो

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set Executable Permission
        run: chmod +x *

      - name: Run the Script
        run: python3 FLASH.py
